### ISSUE TITLE
Saving Cometa Motion File - Wrong Sensor ID

### ISSUE THREAD

**Issue by nicola-lopomo** [paolo-mosna/phoenics#12]
For all the analysed files, the attribute concerning the sensors ID are always set to 9, 10, 11, 12, as here-reported:

```
<sensors>
		<sensor>
			<id>12</id>
			<position>HAND</position>
		</sensor>
		<sensor>
			<id>11</id>
			<position>FOREARM</position>
		</sensor>
		<sensor>
			<id>10</id>
			<position>ARM</position>
		</sensor>
		<sensor>
			<id>9</id>
			<position>CEST</position>
		</sensor>
	</sensors>
```
Though the Motion was acquired by the sensor with different IDs, such as:

```
               <sample id="10" type="quaternion" timestamp="368" x="-0,313" y="-0,546" z="0,326" w="-0,705" />
		<sample id="12" type="quaternion" timestamp="368" x="-0,141" y="0,221" z="0,204" w="-0,943" />
		<sample id="14" type="quaternion" timestamp="368" x="0,000" y="0,000" z="0,000" w="1,000" />
		<sample id="15" type="quaternion" timestamp="368" x="0,000" y="0,000" z="0,000" w="1,000" />
```

**Comment by paolo-mosna** [comment]
Certo, loro avrebbero dovuto specificare l'accoppiamento ID sensore parte del corpo da GUI, ma non lo hanno fatto mettendo i sensori a caso.
Se non si sono segnati come hanno messo i sensori mi sa che dobbiamo recuperare l'informazione dai dati. Nell'esemio i sensori utilizzati sono stati 10, 12, 4 e 15

**Comment by nicola-lopomo** [comment]
Sono stati istruiti a cambiare l'ID del sensore dalla GUI. Gliel'ho fatto
vedere più volte. Venerdì verifichiamo questa cosa..

Nx

Il mar 10 set 2019, 19:49 paolo-mosna <notifications@github.com> ha scritto:
