### ISSUE TITLE
Wrong Quaternion Information

### ISSUE THREAD

**Issue by nicola-lopomo** [paolo-mosna/phoenics#13]
In both the calibration and motion files related to Cometa, there are always 2 sensors with wrong quaternion information:

```
	<sample id="14" type="quaternion" timestamp="363" x="0.000" y="0.000" z="0.000" w="1.000" />
		<sample id="15" type="quaternion" timestamp="363" x="0.000" y="0.000" z="0.000" w="1.000" />
```

They are always fixed to [1 0 0 0] value!

**Comment by paolo-mosna** [comment]
Bella li. Se non vanno  non vanno.....certo che avrebbero dovuto controllare o erano scarichi o non erano collegari....ma il lampeggio del lse segnala lo stato del sensore.

**Comment by paolo-mosna** [comment]
Fixed.
